// src/services/agent/contracts/actionHandler.ts
// BOW AGENT V3.3 — STEP 1: SEMANTIC ACTION CONTRACT
//
// Defines semantic agent actions detached from browser DOM, React components,
// modal states, or window event dispatchers.

import type {
  AgentAction,
  AgentActionType,
  AgentActionPayload,
  AgentContext,
} from '../types';

export type { AgentAction, AgentActionType, AgentActionPayload };

export interface ActionResult {
  success: boolean;
  actionId: string;
  type: AgentActionType;
  message?: string;
  clientPayload?: Record<string, any>;
  handledLocally?: boolean;
}

/**
 * ActionHandler Interface
 * The Host Application (Shop or Robot) implements this interface to handle
 * actions generated by the Agent (e.g. checkout navigation, order query, deposit modal).
 * The Agent Core produces purely semantic actions and has zero DOM or React knowledge.
 */
export interface ActionHandler {
  /**
   * Execute or route a semantic AgentAction
   */
  handleAction(action: AgentAction, context: AgentContext): Promise<ActionResult>;

  /**
   * Validate if an action is supported by the current host environment
   */
  canHandleAction(actionType: AgentActionType): boolean;
}
