import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { supabase } from '../../lib/supabase';
import { sendTicketTelegramNotify } from '../../lib/notify';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../Toast';
import { CloseIcon } from '../icons';

interface OrderOption {
  id: string;
  product_name: string;
  plan_label: string;
  payment_code: string;
  status: string;
}

interface Props {
  isOpen: boolean;
  onClose: () => void;
  initialOrderId?: string | null;
  onTicketCreated: (ticketId: string) => void;
}

export default function CreateTicketModal({
  isOpen,
  onClose,
  initialOrderId,
  onTicketCreated,
}: Props) {
  const { session } = useAuth();
  const toast = useToast();
  const [orders, setOrders] = useState<OrderOption[]>([]);
  const [loadingOrders, setLoadingOrders] = useState(false);

  const [selectedOrderId, setSelectedOrderId] = useState<string>(initialOrderId || '');
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  useEffect(() => {
    if (initialOrderId) {
      setSelectedOrderId(initialOrderId);
    }
  }, [initialOrderId]);

  // Load user orders for dropdown
  useEffect(() => {
    if (!isOpen || !session?.user?.id) return;
    const fetchUserOrders = async () => {
      setLoadingOrders(true);
      try {
        const { data } = await supabase
          .from('orders')
          .select('id, product_name, plan_label, payment_code, status')
          .eq('user_id', session.user.id)
          .order('created_at', { ascending: false });
        setOrders(data || []);
      } catch (e) {
        console.error('Failed to load user orders:', e);
      } finally {
        setLoadingOrders(false);
      }
    };
    fetchUserOrders();
  }, [isOpen, session?.user?.id]);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!session?.user?.id) return;
    if (!subject.trim()) {
      setErrorMsg('Vui lòng nhập chủ đề yêu cầu.');
      return;
    }
    if (!message.trim()) {
      setErrorMsg('Vui lòng nhập nội dung chi tiết.');
      return;
    }

    setSubmitting(true);
    setErrorMsg(null);

    try {
      // 1. Check if an OPEN ticket (pending or processing) already exists for this order
      if (selectedOrderId) {
        const { data: existing } = await (supabase
          .from('support_tickets')
          .select('id, ticket_number')
          .eq('user_id', session.user.id)
          .eq('order_id', selectedOrderId)
          .in('status', ['pending', 'processing'])
          .maybeSingle() as any);

        if (existing) {
          toast.info(`Đơn hàng này đang có Ticket mở (${existing.ticket_number}). Bạn sẽ được chuyển tới Ticket đó.`);
          onTicketCreated(existing.id);
          onClose();
          return;
        }
      }

      // 2. Insert ticket (ticket_number generated by DB trigger)
      const { data: ticket, error: ticketErr } = await (supabase
        .from('support_tickets') as any)
        .insert({
          user_id: session.user.id,
          order_id: selectedOrderId || null,
          subject: subject.trim(),
          status: 'pending',
          priority: 'normal',
        })
        .select('id, ticket_number')
        .single();

      if (ticketErr) throw ticketErr;

      // 3. Insert initial message
      const { error: msgErr } = await (supabase
        .from('support_messages') as any)
        .insert({
          ticket_id: ticket.id,
          sender_id: session.user.id,
          sender_role: 'user',
          message: message.trim(),
        });

      if (msgErr) throw msgErr;

      // 4. Create admin notification
      const userEmail = session.user.email || 'Khách hàng';
      await (supabase.from('notifications') as any).insert({
        is_admin: true,
        type: 'ticket_created',
        title: `🎫 Ticket mới ${ticket.ticket_number}`,
        message: `${userEmail}: ${subject.trim()}`,
      });

      // 5. Send Telegram notification to Admin Bot
      sendTicketTelegramNotify(ticket.id, 'ticket_created', message.trim()).catch(() => {});

      toast.success(`Tạo yêu cầu ${ticket.ticket_number} thành công!`);
      setSubject('');
      setMessage('');
      onTicketCreated(ticket.id);
      onClose();

    } catch (err: any) {
      console.error('Failed creating ticket:', err);
      setErrorMsg(err.message || 'Lỗi khi tạo Ticket hỗ trợ. Vui lòng thử lại.');
    } finally {
      setSubmitting(false);
    }
  };

  return createPortal(
    <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4">
      <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-sm transition-opacity" onClick={onClose} />

      <div className="relative z-[100000] w-full max-w-lg overflow-hidden rounded-[28px] border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#131C32] p-6 shadow-2xl space-y-5 animate-scale-up">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800/80 pb-4">
          <div>
            <h3 className="text-lg font-black text-slate-900 dark:text-white flex items-center gap-2">
              <span>🎫</span> Tạo yêu cầu hỗ trợ mới
            </h3>
            <p className="text-xs text-slate-400 font-semibold mt-0.5">
              Đội ngũ kĩ thuật BOW sẽ kiểm tra và phản hồi trực tiếp qua kênh Chat.
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
          >
            <CloseIcon className="h-5 w-5" />
          </button>
        </div>

        {errorMsg && (
          <div className="rounded-2xl border border-rose-200 bg-rose-50 dark:bg-rose-950/40 p-3 text-xs font-bold text-rose-600 dark:text-rose-400">
            ⚠️ {errorMsg}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Order Selection */}
          {initialOrderId ? (
            <div className="rounded-2xl border border-blue-100 dark:border-blue-900/40 bg-blue-50/50 dark:bg-[#18243E] p-3.5 flex items-center justify-between text-xs shadow-2xs">
              <div className="space-y-0.5 min-w-0 pr-2">
                <span className="text-[10px] font-black uppercase text-[#2563EB] dark:text-[#35A8FF] block">
                  Đơn hàng cần hỗ trợ
                </span>
                <span className="font-extrabold text-slate-900 dark:text-white text-xs block truncate">
                  {orders.find((o) => o.id === selectedOrderId)
                    ? `#${orders.find((o) => o.id === selectedOrderId)?.payment_code} - ${orders.find((o) => o.id === selectedOrderId)?.product_name} (${orders.find((o) => o.id === selectedOrderId)?.plan_label})`
                    : 'Đang tải thông tin đơn hàng...'}
                </span>
              </div>
              <span className="text-2xl shrink-0">📦</span>
            </div>
          ) : (
            <div className="relative">
              <label className="block text-xs font-black uppercase text-slate-500 dark:text-slate-400 mb-1.5">
                Đơn hàng liên quan (Không bắt buộc)
              </label>

              <button
                type="button"
                disabled={loadingOrders}
                onClick={() => setDropdownOpen(!dropdownOpen)}
                className="w-full flex items-center justify-between rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-[#18243E] px-4 py-3 text-xs font-bold text-slate-900 dark:text-white hover:border-[#2563EB] dark:hover:border-[#35A8FF] transition shadow-2xs cursor-pointer"
              >
                <div className="flex items-center gap-2 truncate">
                  <span>📦</span>
                  <span className="truncate">
                    {selectedOrderId
                      ? (() => {
                          const selected = orders.find((o) => o.id === selectedOrderId);
                          return selected
                            ? `#${selected.payment_code} - ${selected.product_name} (${selected.plan_label})`
                            : '-- Chọn đơn hàng cần hỗ trợ --';
                        })()
                      : '-- Chọn đơn hàng cần hỗ trợ (Tùy chọn) --'}
                  </span>
                </div>
                <span className={`text-slate-400 text-[10px] transition-transform duration-200 ${dropdownOpen ? 'rotate-180' : ''}`}>
                  ▼
                </span>
              </button>

              {/* Custom Dropdown Floating Panel */}
              {dropdownOpen && (
                <div className="absolute left-0 right-0 top-full mt-1.5 z-[100050] max-h-56 overflow-y-auto rounded-2xl border border-[#E8F1FF] dark:border-[#1E2A4A] bg-white dark:bg-[#18243E] p-1.5 shadow-2xl space-y-1 animate-fade-in">
                  <button
                    type="button"
                    onClick={() => {
                      setSelectedOrderId('');
                      setDropdownOpen(false);
                    }}
                    className={`w-full text-left px-3.5 py-2.5 rounded-xl text-xs font-bold transition flex items-center justify-between ${
                      selectedOrderId === ''
                        ? 'bg-blue-50 dark:bg-blue-950/60 text-[#2563EB] dark:text-[#35A8FF]'
                        : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/80'
                    }`}
                  >
                    <span>-- Không gắn đơn hàng (Hỗ trợ chung) --</span>
                    {selectedOrderId === '' && <span>✓</span>}
                  </button>

                  {orders
                    .filter((o) => !o.product_name.includes('Nạp tiền'))
                    .map((o) => {
                      const isSelected = selectedOrderId === o.id;
                      return (
                        <button
                          key={o.id}
                          type="button"
                          onClick={() => {
                            setSelectedOrderId(o.id);
                            setDropdownOpen(false);
                          }}
                          className={`w-full text-left px-3.5 py-2.5 rounded-xl text-xs font-extrabold transition flex items-center justify-between gap-2 ${
                            isSelected
                              ? 'bg-gradient-to-r from-[#19A7FF] to-[#2563EB] text-white shadow-xs'
                              : 'text-slate-800 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800/80'
                          }`}
                        >
                          <div className="truncate">
                            <span className="font-mono text-xs opacity-90 mr-1.5">#{o.payment_code}</span>
                            <span>{o.product_name}</span>
                            <span className="text-[10px] font-normal opacity-75 ml-1">({o.plan_label})</span>
                          </div>
                          {isSelected && <span className="shrink-0">✓</span>}
                        </button>
                      );
                    })}
                </div>
              )}
            </div>
          )}

          {/* Subject */}
          <div>
            <label className="block text-xs font-black uppercase text-slate-500 dark:text-slate-400 mb-1.5">
              Chủ đề yêu cầu <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              placeholder="VD: Không đăng nhập được tài khoản, Cần đổi mật khẩu..."
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              required
              className="w-full rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3.5 py-2.5 text-xs font-bold text-slate-900 dark:text-white focus:border-[#2563EB] focus:outline-none transition"
            />
          </div>

          {/* Message */}
          <div>
            <label className="block text-xs font-black uppercase text-slate-500 dark:text-slate-400 mb-1.5">
              Nội dung chi tiết <span className="text-rose-500">*</span>
            </label>
            <textarea
              rows={4}
              placeholder="Mô tả cụ thể vấn đề hoặc thông tin lỗi bạn đang gặp phải..."
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              required
              className="w-full rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3.5 py-2.5 text-xs font-medium text-slate-900 dark:text-white focus:border-[#2563EB] focus:outline-none transition resize-none"
            />
          </div>

          {/* Buttons */}
          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              disabled={submitting}
              className="flex-1 rounded-full border border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 py-2.5 text-xs font-bold text-slate-700 dark:text-slate-200 disabled:opacity-60 transition"
            >
              Hủy
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="flex-1 rounded-full bg-gradient-to-r from-[#19A7FF] to-[#2563EB] hover:from-[#19A7FF] hover:to-[#1D4ED8] py-2.5 text-xs font-bold text-white shadow-md disabled:opacity-60 transition"
            >
              {submitting ? 'Đang gửi...' : '🚀 Gửi yêu cầu'}
            </button>
          </div>
        </form>
      </div>
    </div>,
    document.body
  );
}
